#undef TAPPING_TERM
#define TAPPING_TERM 225

// Cancel one-shot after one and a half second
#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1500

#define PERMISSIVE_HOLD

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

// Smart caps lock cancels after 10 seconds.
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 10000

// Navigation layer lock cancels after 10 seconds.
#define LAYER_LOCK_IDLE_TIMEOUT 10000

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60
#define RGB_MATRIX_DEFAULT_SPD 20

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 10
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 80
#undef MOUSEKEY_WHEEL_DELTA
#define MOUSEKEY_WHEEL_DELTA 1
#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define MK_KINETIC_SPEED
// #define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 16
// #define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
// #define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 48
// #define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 8
